# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: bd070a8666e76e4e894084e78e7b4036497ce6dc872d58b49654c5fa0828a85481f78a692301c0dbf1c936d3a803fd7f03b73ccd7e5f28e61453a39b0c66ff8a

test:
  secret_key_base: a65681c737bdfc2d4d0211e80e7b2817f08522a9c5bcf0d509e42e43f26a6fc5992cf86213d669176d860839b40720e035075eb229c392bd5febbacffc9f5b51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
