development:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: bd070a8666e76e4e894084e78e7b4036497ce6dc872d58b49654c5fa0828a85481f78a692301c0dbf1c936d3a803fd7f03b73ccd7e5f28e61453a39b0c66ff8a

test:
  secret_key_base: a65681c737bdfc2d4d0211e80e7b2817f08522a9c5bcf0d509e42e43f26a6fc5992cf86213d669176d860839b40720e035075eb229c392bd5febbacffc9f5b51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


# development:
#   omniauth_provider_key: fVN7ylrcT6OG5PeZ6NQBNkJxm
#   omniauth_provider_secret: 6ao8fbGCT1kWfWaYJ3itFLWgPozc9NyxWBrfoOcy3mB0SHN9hX
#   domain_name: example.com
#   secret_key_base: bd070a8666e76e4e894084e78e7b4036497ce6dc872d58b49654c5fa0828a85481f78a692301c0dbf1c936d3a803fd7f03b73ccd7e5f28e61453a39b0c66ff8a

# test:
#   secret_key_base: a65681c737bdfc2d4d0211e80e7b2817f08522a9c5bcf0d509e42e43f26a6fc5992cf86213d669176d860839b40720e035075eb229c392bd5febbacffc9f5b51

# # Do not keep production secrets in the repository,
# # instead read values from the environment.
# production:
#   omniauth_provider_key: fVN7ylrcT6OG5PeZ6NQBNkJxm
#   omniauth_provider_secret: 6ao8fbGCT1kWfWaYJ3itFLWgPozc9NyxWBrfoOcy3mB0SHN9hX
#   domain_name: <%= ENV["DOMAIN_NAME"] %>
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
